function esc(s) {
  return String(s || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// This view owns its albums outright. It used to share data.js and localStorage with the
// timeline, which meant deleting or reordering an album here changed the timeline too -
// hence the old rule that only bestOfYearOnly albums could be deleted. The stores are now
// forked: bestof-data.js is this page's, data.js is the timeline's, and the 176 albums
// that appear on both sides exist as independent copies.
const ENTRIES = BEST_OF_ENTRIES;

const LS_KEY = 'indie_bestofyear_v1';
const LEGACY_LS_KEY = 'indie_timeline_v1';

// 2: every Spotify `audio` link was replaced with an Apple preview in the data files, but
//    saved entries win over baked ones and backfill only fills *blank* fields — so a stale
//    blob kept replaying the old Spotify embeds. Heal them from the baked twin once.
// 3: same trap, wider: every `audio` value in bestof-data.js was machine-generated by the
//    import scripts, so when one is corrected by hand (picking a better track, say) the
//    saved copy still shadows it. Take the baked `audio` wholesale, once.
// 4: hand-picked tracks for Grouper, Pinback and Kanye West. BUMP THIS EVERY TIME an `audio`
//    link is corrected by hand, or the fix sits in bestof-data.js and never reaches anyone
//    who already has a saved copy of that album.
// 5: hand-picked tracks for Unwound and Aaliyah; Joanna Newsom moved off YouTube.
// 6: hand-picked tracks for Jill Scott and Madonna; Godspeed You! Black Emperor's link was
//    someone else's song entirely and is now cleared (they aren't on streaming).
// 7: The Field's From Here We Go Sublime plays its title track rather than "Everyday".
// 8: the 2010s import. Also re-takes `yearRank` for 2010-2019 - see RERANKED_YEARS.
// 9: hand-picked tracks for Lady Gaga's The Fame ("Poker Face"), Kelis's Tasty
//    ("Milkshake"), Dinosaur Jr.'s Farm ("Pieces") and Autolux's Future Perfect
//    ("Asleep at the Trigger").
// 10: hand-picked tracks for ROSALÍA's EL MAL QUERER ("MALAMENTE") and Robyn's Honey (the
//    title track). A separate bump rather than an extension of 9 - 9 may already have been
//    loaded once, and the heal only fires when the saved version is behind the current one.
// 11: The Avalanches' Wildflower had the cover *and* the preview of another release. First
//    time `art` has been corrected by hand - see REHEAL_ART_KEYS, since the audio heal has
//    never touched art. Track is now "Because I'm Me".
// 12: hand-picked tracks for Blood Orange's Freetown Sound ("Best to You"), Weyes Blood's
//    Front Row Seat to Earth ("Do You Need My Love") and Mitski's Puberty 2 ("Your Best
//    American Girl"). All three already had the right album - preference, not repair.
// 13: hand-picked tracks for Joanna Newsom's Have One On Me ("In California"), Arcade Fire's
//    The Suburbs ("Sprawl II") and Taylor Swift's Speak Now ("Enchanted"). All three albums
//    were already correct - preference, not repair.
// 14: hand-picked tracks for Lana Del Rey's Norman Fucking Rockwell! ("Venice Bitch") and
//    FKA Twigs's MAGDALENE ("mary magdalene"). Both albums were already correct.
// 15: MAGDALENE moved off "mary magdalene" to "fallen alien" - a second pass at the same
//    entry, so 14's heal may already have run and this needs its own bump.
// 16: the 2020s import (2020-2024, 192 albums). Establishes `yearRank` for those five years
//    - see RERANKED_YEARS, which from this version on is scoped per year *and* per version,
//    so bumps 10-15 can no longer keep resetting the 2010s order the way they had been.
// 17: the pre-2000 import (1969, 1993, 1994, 1997, 1998 - 70 albums). Same deal: it sets
//    `yearRank` for five more years, so they join RERANKED_YEARS at this version and no
//    other year's order is touched. Also carries two audio corrections - Illmatic and
//    I Can Hear the Heart Beating As One were previewing their spoken-word/instrumental
//    openers, which gapfill.pick now filters out (see _no_runts there).
// 18: the rest of pre-2000 (1954-1999, 219 albums), which sets `yearRank` for the remaining
//    thirty-nine years - they join RERANKED_YEARS here and nothing already ranked is touched.
//    Six albums that existed twice under two spellings ("The Replacement"/"The Replacements",
//    Wipers' "Youth in America"/"Youth of America" and four more) were merged down to one
//    entry each, keeping the hand-written tagline and tier from the older copy; the years
//    around them were renumbered to close the gaps, which is the other reason for the bump.
// 19: 2025 and 2026 (7 albums), which is the sheet exhausted - every row in it is now on the
//    site. Sets `yearRank` for both years, and retires the two blank placeholder rows 2026
//    had been sitting on - see RETIRED_KEYS, which has to reach saved copies too.
// 20: two previews picked by hand - 青葉市子's アダンの風 to 'Porcelain' and Taylor Swift's
//    evermore to 'closure'. Both had a track a saved copy already holds a non-blank `audio`
//    for, so backfillEmptyFields cannot reach them and only the bump can.
// 21: same again, Car Seat Headrest's Twin Fantasy to 'Beach Life-In-Death'. Its own bump
//    rather than folding into 20, because 20 had already been written to disk: a save made in
//    between sits at 20, and healAudio only fires while savedVersion is strictly lower.
// 22: and Kacey Musgraves' Golden Hour to 'High Horse'. Its own number for the same reason as
//    21: each of these arrives after the one before it is already on disk.
// 23: Father John Misty's I Love You, Honeybear to 'Holy Shit'. Ditto.
// 24: three more, all 2015 - Joanna Newsom's Divers to 'Time, As a Symptom', Courtney
//    Barnett's Sometimes I Sit and Think to 'Pedestrian at Best', and Natalia Lafourcade's
//    Hasta la Raíz to 'Mi Lugar Favorito'. One number for the three because they were picked
//    together and written in one go - the rule is one bump per write to disk, not per album.
// 25: two from 2017 - Lorde's Melodrama to 'Supercut' and Big Thief's Capacity to
//    'Mythological Beauty'.
// 26: Slowdive's Pygmalion to "Blue Skied an' Clear". PJ Harvey's Let England Shake was added
//    to 2011 in the same write and is NOT why this bumped - it arrives through `additions`
//    either way, and it took rank 13 above a full 1..12, so no existing order moved.
// 27: The Smashing Pumpkins' Siamese Dream to 'Geek U.S.A.'.
// 28: Let England Shake to 'On Battleship Hill', and its rating off the unscored placeholder
//    of 3 to 4. The rating is why REHEAL_RATING_KEYS exists - a copy saved at 26 or 27 has
//    the placeholder and nothing below would ever have replaced it.
// 29: three from 1996 - Low's The Curtain Hits the Cast to 'Coattails', Tori Amos's Boys for
//    Pele to 'Caught a Lite Sneeze' and Fugees' The Score to 'No Woman, No Cry'.
// 30: two from 2014 - Taylor Swift's 1989 to 'Wildest Dreams' and Sun Kil Moon's Benji to
//    'Carissa'. 1989 resolves to the 2014 release, not Taylor's Version.
// 31: Death Grips' The Money Store to 'Get Got'. The album arrived minutes earlier with the
//    2012 addendum rows, which did not bump - so a copy saved in between holds the importer's
//    pick ("I've Seen Footage"). Audio is re-taken wholesale on any bump, so this reaches it.
// 32: six from 2026 - Olivia Rodrigo's you seem pretty sad for a girl so in love to 'the cure',
//    Phoebe Bridgers' Lost Weekend to "The Governor's Waltz", Madonna's to 'Danceteria',
//    Mandy, Indiana's URGH to 'Cursive', Boards of Canada's Inferno to 'Naraka' and Charli
//    XCX's Wuthering Heights to 'Dying for You'. All six arrived with the current-years import
//    the day before, so a copy saved in between holds the importer's picks.
//
//    Madonna's was also renamed here, from the sheet's 'Confessions 2' to Apple's CONFESSIONS
//    II, and that half is not what the bump is for - see RETIRED_KEYS, which is what actually
//    carries a rename to a saved copy. It needed a version to fire at and this is the one.
//
// 33: L'Rain's fata morgana added to 2026 at #7 by hand. The album arriving is not the reason
//    for the bump - `additions` would carry it to a save on its own, as it does for every
//    import. Inserting it is: the fifteen albums from Debit's Potpourri down were renumbered
//    to make room, and a v32 save holds its own copy of all fifteen at the old number. Without
//    the heal it would show two #7s, two #8s and so on to the bottom of the year. See
//    RERANKED_YEARS, where 2026 moves from 19 to 33 for exactly this.
//
// The imports that landed among these deliberately did NOT bump - the 'addendum' pass (24
// albums into sixteen years already on the site) and the two 'current' passes (26 into 2025 and
// 2026, same shape) - and the distinction is the rule to follow: `additions` and
// backfillEmptyFields below run regardless of version, so albums *added* alongside a save
// arrive either way, while a bump re-takes `audio` for every entry. Bump when baked data the
// save already has its own copy of changes underneath it - which is what these twenty-four are
// and adding a new album is not. Filling a blank field on an album already saved is not it
// either: Madonna's art and audio were backfilled between 31 and 32 without one, because
// backfillEmptyFields reaches a blank on its own.
//
// 33 is the line between those two: an album *appended* to a year changes nothing anyone
// already has, an album *inserted* into one renumbers everything under it. Same act from the
// editor's side, opposite answers - what decides it is whether existing entries moved, not
// whether an entry was added.
//
// Those years are likewise absent from RERANKED_YEARS: every one of those imports appended to a
// running order instead of rewriting it, so there is nothing to heal. These bumps cannot disturb
// the order either - every year involved has sat in RERANKED_YEARS since its own import, at 19
// or below, and any save new enough to be affected here is well past that. 33 is the exception
// and is scoped to the one year it renumbered.
const STORAGE_SCHEMA_VERSION = 33;

// Deleting can't just drop the entry from ENTRIES: the loader re-adds anything present
// in bestof-data.js but missing from the saved set (so new imports show up), and a
// deleted entry is exactly that - it would come straight back on reload. Deletes leave a
// tombstone here, and the loader skips additions that carry one.
const DELETED_KEYS = new Set();

// tierLabels - the display names for the badges above each title - lived here until the badges
// were dropped from the card. tierWeight below is a different thing and is still live: it has
// no text, it only orders a year nobody has ranked yet.
const tierWeight = {
  essential: 3,
  pioneer: 2,
  postinfluence: 1,
  influence: 0
};

function stars(n) {
  return [1, 2, 3, 4, 5].map(i => (i <= n ? '★' : '☆')).join('');
}

function albumArt(entry) {
  if (entry.art) {
    return `<img src="${esc(entry.art)}" alt="${esc(entry.title)} album art" loading="lazy">`;
  }

  return `
    <div class="year-art-fallback" style="background:${esc(entry.artBg || '#181818')};color:${esc(entry.artColor || '#999')}">
      <div>${esc(entry.title)}<br><span style="opacity:.65">${esc(entry.artist)}</span></div>
    </div>
  `;
}

function audioEmbedHtml(url) {
  if (!url) return '';
  const sp = url.match(/open\.spotify\.com\/(track|album|playlist|episode)\/([A-Za-z0-9]+)/);
  if (sp) {
    return `<iframe src="https://open.spotify.com/embed/${sp[1]}/${sp[2]}?utm_source=generator" height="152" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>`;
  }
  const yt = url.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/)([A-Za-z0-9_-]+)/);
  if (yt) {
    return `<a class="year-action" href="${esc(url)}" target="_blank" rel="noopener">Watch on YouTube</a>`;
  }
  if (url.includes('soundcloud.com')) {
    return `<a class="year-action" href="${esc(url)}" target="_blank" rel="noopener">Listen on SoundCloud</a>`;
  }
  if (/\.(mp3|ogg|wav|m4a|aac|flac)(\?|$)/i.test(url)) {
    return `<audio controls><source src="${esc(url)}">Your browser doesn't support audio.</audio>`;
  }
  return `<a class="year-action" href="${esc(url)}" target="_blank" rel="noopener">Open link</a>`;
}

function excerpt(...parts) {
  return parts.find(Boolean) || '';
}

function yearLink(year) {
  return `best-of-year.html?year=${encodeURIComponent(year)}`;
}

function persist() {
  try {
    // Anything back in ENTRIES - re-added by hand, or renamed onto a dead key - must
    // lose its tombstone here, or the next load would delete it all over again.
    ENTRIES.forEach(entry => DELETED_KEYS.delete(entryKey(entry)));
    localStorage.setItem(LS_KEY, JSON.stringify({
      storageSchemaVersion: STORAGE_SCHEMA_VERSION,
      entries: ENTRIES,
      deleted: [...DELETED_KEYS],
    }));
  } catch (e) {
    // Ignore persistence failures in private browsing or quota limits.
  }
}

function entryKey(entry) {
  // Strip accents and punctuation, but keep letters/digits of ANY script - a
  // /[^a-z0-9]/ strip collapses CJK titles to '', making every such album collide.
  const norm = value => String(value || '')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]/gu, '');
  return `${entry.type}|${entry.year}|${norm(entry.title)}|${norm(entry.artist)}`;
}

// A saved copy predating a data.js change keeps its blank fields forever, so an album
// imported before its audio link existed would never grow a Listen button. Only fills
// gaps — anything the user actually typed wins.
function backfillEmptyFields(saved, baked) {
  if (!baked) return saved;
  const blank = value => value === undefined || value === null || value === ''
    || (Array.isArray(value) && !value.length);
  Object.keys(baked).forEach(field => {
    if (blank(saved[field]) && !blank(baked[field])) saved[field] = baked[field];
  });
  return saved;
}

// A saved entry carries its own non-blank `audio`, so it slips past backfillEmptyFields and
// shadows the data file forever — which is why swapping the Spotify embeds for Apple previews
// appeared to do nothing. Every `audio` here came from the import scripts rather than the
// editor, so the baked value is the better source; take it wholesale. Gated on the schema
// version, so this runs once and a link chosen in the editor afterwards is left alone.
// Mirrors the baked value exactly, including *absence* of one: when a link turns out to be
// plain wrong (the wrong band's song) the fix is to clear it, and bailing out on a blank
// baked `audio` would leave the bad link sitting in every saved copy forever.
function healAudioFromBaked(entry, baked) {
  if (!baked) return entry;
  entry.audio = baked.audio || '';
  return entry;
}

// Years whose running order an import established, mapped to the schema version that did it.
// sortedYearAlbums auto-numbers and *persists* a rank for any year you merely look at, so an
// album that sat alone in its year already has `yearRank: 1` saved — non-blank, so
// backfillEmptyFields leaves it alone and it collides with the newly imported album that
// should outrank it. Take the baked rank, but only for these years: elsewhere the order may
// have been set deliberately with the ▲▼ controls.
//
// The *version* half matters as much as the year half. This used to be a bare Set fired from
// the same flag as the audio heal, which goes true on every bump — so versions 10-15, all of
// them audio-only track swaps, each re-took the baked order for 2010-2019 and threw away
// re-ranking done in between. Heal only when the saved copy predates the import that set the
// order. Add years here as each decade lands, with the version that imported it.
const RERANKED_YEARS = new Map([
  ...[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019].map(y => [y, 8]),
  ...[2020, 2021, 2022, 2023, 2024].map(y => [y, 16]),
  ...[1969, 1993, 1994, 1997, 1998].map(y => [y, 17]),
  // Everything else before 2000. Written as the range minus what 17 already claimed rather
  // than as thirty-nine literals - the five above must keep their own version, or a v17 save
  // would have its hand-ranking of those years taken back. 1957 and 1958 have no entries yet
  // and cost nothing to carry.
  ...Array.from({ length: 46 }, (_, i) => 1954 + i)
    .filter(y => ![1969, 1993, 1994, 1997, 1998].includes(y))
    .map(y => [y, 18]),
  [2025, 19],
  // 2026 is at 33, not the 19 its import set, because the order has been rewritten since:
  // L'Rain went in at #7 by hand and pushed fifteen albums down a place. A v32 save holds the
  // pre-insert numbers for all fifteen, so it has to take the baked order or the year carries
  // a duplicate at every rank from 7 down. Raising 2026's version rather than adding a second
  // entry for it keeps the invariant that a year appears once here; 2025 is untouched by the
  // insert and stays at the version that imported it.
  [2026, 33],
]);

// Entries dropped from bestof-data.js that must also go from an existing save. Removing an
// album from the baked list is not enough on its own: the loader replays `saved.entries`
// verbatim, so anything already saved survives its own deletion. DELETED_KEYS is no help
// either - that only suppresses *re-additions*, and there is nothing left to re-add.
//
// Versioned like RERANKED_YEARS, and for the same reason: the purge has to stop firing once
// everyone has passed it, or an entry the editor legitimately re-creates later would keep
// being swept away on every subsequent bump.
const RETIRED_KEYS = new Map([
  // Two blank rows - literally 'Artist' / 'New Album', no art, audio or text - left behind by
  // the editor's add button. 2026 had nothing else in it until this import, so they had never
  // been noticeable before.
  ['album|2026|newalbum|artist', 19],
  // Not a deletion but a rename: Madonna's 2026 album is styled CONFESSIONS II and was
  // imported under the sheet's 'Confessions 2'. Title is part of entryKey, so the renamed
  // entry is a different album as far as the loader is concerned - `additions` brings in
  // CONFESSIONS II and the old row, which nothing now matches, would sit there beside it.
  // Retiring the old key is what makes a rename one album rather than two.
  ['album|2026|confessions2|madonna', 32],
]);

function dropRetired(entries, savedVersion) {
  return entries.filter(entry => {
    const since = RETIRED_KEYS.get(entryKey(entry));
    return since === undefined || savedVersion >= since;
  });
}

function healYearRankFromBaked(entry, baked, savedVersion) {
  const since = RERANKED_YEARS.get(entry.year);
  if (!baked || since === undefined || savedVersion >= since) return entry;
  if (Number.isFinite(baked.yearRank)) entry.yearRank = baked.yearRank;
  return entry;
}

// Albums whose `art` was pointing at the wrong record and has since been corrected by hand,
// mapped to the schema version that corrected it. The bump re-takes `audio` for everything,
// but not `art`: cover images can be set deliberately in the editor, and taking the baked one
// wholesale would silently undo that. So art is healed only for the keys named here, and -
// as with RERANKED_YEARS - only for saves older than the fix, or a later unrelated bump would
// keep overwriting a cover chosen in the editor afterwards. Add a key whenever an `art` URL
// is fixed by hand, with the version that fixed it; drop it once it's long shipped.
const REHEAL_ART_KEYS = new Map([
  // Resolved to some other release entirely - neither the cover nor the preview belonged
  // to the 2016 Avalanches record.
  ['album|2016|wildflower|theavalanches', 11],
]);

function healArtFromBaked(entry, baked, savedVersion) {
  const since = REHEAL_ART_KEYS.get(entryKey(entry));
  if (!baked || since === undefined || savedVersion >= since) return entry;
  if (baked.art) entry.art = baked.art;
  return entry;
}

// `rating` is the one field the editor owns outright, so there is no general heal for it -
// re-taking it wholesale would wipe every star set by hand. It still needs a way through for
// one case: an album added here rather than imported arrives carrying the unscored placeholder
// of 3, and a saved copy that has already picked that up keeps it forever, because
// backfillEmptyFields only fills blanks and 3 is not blank. Same shape as REHEAL_ART_KEYS -
// name the entry and the version that corrected it, and no other rating anywhere moves.
const REHEAL_RATING_KEYS = new Map([
  // Added at 26 on the unscored default, scored by hand two versions later.
  ['album|2011|letenglandshake|pjharvey', 28],
]);

function healRatingFromBaked(entry, baked, savedVersion) {
  const since = REHEAL_RATING_KEYS.get(entryKey(entry));
  if (!baked || since === undefined || savedVersion >= since) return entry;
  if (baked.rating) entry.rating = baked.rating;
  return entry;
}

// Before the fork both views shared one localStorage blob, so a reader arriving with
// edits made under the old scheme has all their year orderings, ratings and reviews
// sitting in the timeline's key. Claim a copy once, rather than silently resetting this
// page to the baked-in order. The timeline's blob is left untouched - it still needs it.
function migrateFromSharedStore() {
  try {
    if (localStorage.getItem(LS_KEY)) return null;   // already forked, nothing to do
    const raw = localStorage.getItem(LEGACY_LS_KEY);
    if (!raw) return null;
    const legacy = JSON.parse(raw);
    if (!Array.isArray(legacy.entries) || !legacy.entries.length) return null;
    const mine = legacy.entries.filter(e => e.type === 'album' && !e.hideFromBestOfYear);
    if (!mine.length) return null;
    // hideFromBestOfYear / bestOfYearOnly no longer route anything; the file an entry
    // lives in is what decides which view shows it.
    mine.forEach(e => { delete e.bestOfYearOnly; delete e.hideFromBestOfYear; });
    const migrated = { entries: mine, deleted: Array.isArray(legacy.deleted) ? legacy.deleted : [] };
    localStorage.setItem(LS_KEY, JSON.stringify(migrated));
    return migrated;
  } catch (e) {
    return null;   // corrupted legacy data - fall back to the baked-in albums
  }
}

function loadPersistedEntries() {
  try {
    migrateFromSharedStore();
    const raw = localStorage.getItem(LS_KEY);
    if (!raw) return;
    const saved = JSON.parse(raw);
    if (Array.isArray(saved.deleted)) saved.deleted.forEach(key => DELETED_KEYS.add(key));
    if (!Array.isArray(saved.entries) || !saved.entries.length) return;
    // Saved entries win, but albums added to data.js since the last save still need to
    // show up — otherwise a stale localStorage copy hides every new import. Albums the
    // user deleted are the one exception: they stay gone.
    const savedEntries = dropRetired(saved.entries, saved.storageSchemaVersion || 0);
    const savedKeys = new Set(savedEntries.map(entryKey));
    const additions = ENTRIES.filter(entry => !savedKeys.has(entryKey(entry))
      && !DELETED_KEYS.has(entryKey(entry)));
    const baked = new Map(ENTRIES.map(entry => [entryKey(entry), entry]));
    const savedVersion = saved.storageSchemaVersion || 0;
    const healAudio = savedVersion < STORAGE_SCHEMA_VERSION;
    ENTRIES.length = 0;
    savedEntries.forEach(entry => {
      const twin = baked.get(entryKey(entry));
      let next = backfillEmptyFields(entry, twin);
      if (healAudio) {
        // Audio is re-taken on every bump by design; rank and art carry their own
        // thresholds so an unrelated bump can't undo work done in the editor.
        next = healAudioFromBaked(next, twin);
        next = healArtFromBaked(next, twin, savedVersion);
        next = healRatingFromBaked(next, twin, savedVersion);
        next = healYearRankFromBaked(next, twin, savedVersion);
      }
      ENTRIES.push(next);
    });
    additions.forEach(entry => ENTRIES.push(entry));
    if (healAudio || additions.length) persist();
  } catch (e) {
    // Ignore corrupted local data and fall back to baked-in entries.
  }
}

function compareDefaultYearOrder(a, b) {
  const ratingDiff = (b.entry.rating || 0) - (a.entry.rating || 0);
  if (ratingDiff !== 0) return ratingDiff;

  const tierDiff = (tierWeight[b.entry.tier] || 0) - (tierWeight[a.entry.tier] || 0);
  if (tierDiff !== 0) return tierDiff;

  return a.idx - b.idx;
}

function allAlbums() {
  return ENTRIES
    .map((entry, idx) => ({ entry, idx }))
    // Every album in this store belongs to this view - routing flags are gone.
    .filter(({ entry }) => entry.type === 'album' && Number.isFinite(entry.year));
}

function sortedYearAlbums(year) {
  const albums = allAlbums().filter(({ entry }) => entry.year === year);
  const ranked = albums.every(({ entry }) => Number.isFinite(entry.yearRank));
  const sorted = albums.slice().sort((a, b) => {
    if (Number.isFinite(a.entry.yearRank) || Number.isFinite(b.entry.yearRank)) {
      if (!Number.isFinite(a.entry.yearRank)) return 1;
      if (!Number.isFinite(b.entry.yearRank)) return -1;
      if (a.entry.yearRank !== b.entry.yearRank) return a.entry.yearRank - b.entry.yearRank;
    }
    return compareDefaultYearOrder(a, b);
  });

  if (!ranked && sorted.length) {
    sorted.forEach(({ entry }, i) => {
      entry.yearRank = i + 1;
    });
    persist();
  }

  return sorted;
}

loadPersistedEntries();

const years = [...new Set(allAlbums().map(({ entry }) => entry.year))].sort((a, b) => b - a);
const params = new URLSearchParams(window.location.search);
const requestedYear = Number.parseInt(params.get('year'), 10);
// Always honour the URL year if it's a valid number — even if no albums exist yet for that year,
// so the empty state and "+ Album" modal both work correctly for that year.
const activeYear = Number.isFinite(requestedYear) ? requestedYear : (years[0] || new Date().getFullYear());

let isEditing = false;
let activePlayerIndex = null;

function renderYearNav() {
  // Include activeYear in the nav even if it has no albums yet (e.g. navigated from timeline year label)
  const navYears = years.includes(activeYear)
    ? years
    : [activeYear, ...years].sort((a, b) => b - a);
  document.getElementById('year-nav').innerHTML = navYears
    .map(year => `<a class="year-pill${year === activeYear ? ' is-active' : ''}" href="${yearLink(year)}">${year}</a>`)
    .join('');
}

function renderList() {
  const list = document.getElementById('year-list');
  const yearAlbums = sortedYearAlbums(activeYear);

  document.getElementById('year-title').textContent = `Best Albums of ${activeYear}`;
  // The year blurb is hidden: the list is the argument, and a paragraph restating it above
  // the number one only competes with it. YEAR_NOTES itself is untouched - still in
  // bestof-data.js, still written back out on export - so this is one line to reverse.
  document.getElementById('year-dek').hidden = true;
  document.getElementById('ranking-note').textContent = isEditing
    ? 'Use the arrow buttons to move records up or down within this year. Changes save locally right away — use ⬇ bestof-data.js to write them to disk. This view has its own album list, so edits and deletions here never affect the main timeline.'
    : 'Albums are ordered by your saved year ranking. If a year has never been ranked before, this page seeds the list from your star ratings, special tiers, and original timeline order.';
  document.getElementById('timeline-link').href = 'index.html';
  document.body.classList.toggle('is-editing', isEditing);

  if (!yearAlbums.length) {
    list.innerHTML = `
      <section class="year-empty">
        <h2>No albums for ${esc(activeYear)}</h2>
        <p>There are no album entries tied to this release year yet. Add some on the timeline and this view will populate automatically.</p>
      </section>
    `;
    return;
  }

  list.innerHTML = yearAlbums.map(({ entry }, i) => {
    // `tier` and `tagline`/`review` are no longer rendered here. Both are timeline fields that
    // rode across when the two stores were forked: the tier badge labelled a record's place in
    // the timeline's narrative ('Early Influence' of what, on a page that is one year deep?),
    // and the taglines were written as timeline captions. Only 81 of 985 entries carry a tier
    // and 36 a tagline, so both read as an inconsistency rather than a feature. The fields are
    // left in the data - tierWeight still seeds the order of a year that has never been ranked.
    const tags = (entry.tags || []).map(tag => `<span class="year-tag">${esc(tag)}</span>`).join('');
    const audio = entry.audio
      ? `<button class="year-action" type="button" data-listen="${i}" aria-expanded="${activePlayerIndex === i ? 'true' : 'false'}">${activePlayerIndex === i ? 'Hide player' : 'Listen'}</button>`
      : '';

    const entryIdx = ENTRIES.indexOf(entry);
    return `
      <article class="year-card" style="position:relative">
        <div class="year-rank">
          <div class="year-rank-num">${i + 1}</div>
          <div class="year-rank-controls edit-only">
            <button class="year-rank-btn" type="button" data-move="up" data-rank="${i}" ${i === 0 ? 'disabled' : ''} aria-label="Move ${esc(entry.title)} up">↑</button>
            <button class="year-rank-btn" type="button" data-move="down" data-rank="${i}" ${i === yearAlbums.length - 1 ? 'disabled' : ''} aria-label="Move ${esc(entry.title)} down">↓</button>
            <button class="year-rank-btn year-edit-btn" type="button" data-edit-idx="${entryIdx}" title="Edit">✎</button>
            <button class="year-rank-btn year-del-btn" type="button" data-delete-idx="${entryIdx}" title="Delete">✕</button>
          </div>
        </div>
        <div class="year-art">${albumArt(entry)}</div>
        <div class="year-copy">
          <div class="year-title-row">
            <h2 class="year-album-title">${esc(entry.title)}</h2>
          </div>
          <div class="year-artist">${esc(entry.artist)}</div>
          ${tags ? `<div class="year-tags">${tags}</div>` : ''}
          ${audio ? `<div class="year-actions">${audio}</div>` : ''}
        </div>
      </article>
    `;
  }).join('');
}

function playYearAlbum(index) {
  const yearAlbums = sortedYearAlbums(activeYear);
  const item = yearAlbums[index];
  if (!item || !item.entry.audio) return;
  const entry = item.entry;
  const url = entry.audio;

  const player = document.getElementById('mini-player');
  const iframe = document.getElementById('mini-player-iframe');
  const audio = document.getElementById('mini-player-audio');
  const titleEl = document.getElementById('mini-player-title');

  if (activePlayerIndex === index && player.classList.contains('visible')) {
    closeMiniPlayer();
    return;
  }

  const sp = url.match(/open\.spotify\.com\/(track|album|playlist|episode)\/([A-Za-z0-9]+)/);
  const yt = url.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/)([A-Za-z0-9_-]+)/);
  const sc = url.includes('soundcloud.com');
  const af = /\.(mp3|ogg|wav|m4a|aac|flac)(\?|$)/i.test(url);

  let iframeSrc = '';
  let iframeH = 80;
  let useAudio = false;

  if (sp) {
    iframeSrc = `https://open.spotify.com/embed/${sp[1]}/${sp[2]}?utm_source=generator&autoplay=1&theme=0`;
  } else if (yt) {
    window.open(url, '_blank');
    return;
  } else if (sc) {
    iframeSrc = `https://w.soundcloud.com/player/?url=${encodeURIComponent(url)}&auto_play=true&color=%23ff5500&hide_related=true&show_comments=false&show_teaser=false`;
    iframeH = 120;
  } else if (af) {
    useAudio = true;
  } else {
    window.open(url, '_blank');
    return;
  }

  activePlayerIndex = index;
  titleEl.textContent = `${entry.artist}  —  ${entry.title}`;

  player.style.display = 'block';
  void player.offsetWidth;
  player.classList.add('visible');

  if (useAudio) {
    iframe.style.display = 'none';
    iframe.src = '';
    audio.style.display = 'block';
    audio.src = url;
    audio.play().catch(() => {});
  } else {
    audio.style.display = 'none';
    audio.pause();
    audio.src = '';
    const curIframe = document.getElementById('mini-player-iframe');
    const fresh = document.createElement('iframe');
    fresh.id = 'mini-player-iframe';
    fresh.height = String(iframeH);
    fresh.setAttribute('allow', 'autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture');
    fresh.setAttribute('allowtransparency', 'true');
    fresh.style.cssText = 'width:100%;display:block;border:none';
    fresh.src = iframeSrc;
    curIframe.replaceWith(fresh);
  }

  renderList();
}

function closeMiniPlayer() {
  const player = document.getElementById('mini-player');
  const iframe = document.getElementById('mini-player-iframe');
  const audio = document.getElementById('mini-player-audio');
  player.classList.remove('visible');
  setTimeout(() => {
    player.style.display = 'none';
    iframe.src = '';
    audio.pause();
    audio.src = '';
    activePlayerIndex = null;
    renderList();
  }, 240);
}

function swapYearRank(fromIndex, toIndex) {
  const yearAlbums = sortedYearAlbums(activeYear);
  if (toIndex < 0 || toIndex >= yearAlbums.length) return;
  const reordered = yearAlbums.slice();
  const [moved] = reordered.splice(fromIndex, 1);
  reordered.splice(toIndex, 0, moved);
  reordered.forEach(({ entry }, i) => {
    entry.yearRank = i + 1;
  });
  persist();
  renderList();
}

document.getElementById('year-list').addEventListener('click', event => {
  // Check specific button types before the generic rank-btn catch-all
  const editBtn = event.target.closest('.year-edit-btn');
  if (editBtn && isEditing) {
    openAddAlbumModal(Number.parseInt(editBtn.dataset.editIdx, 10));
    return;
  }

  const delBtn = event.target.closest('.year-del-btn');
  if (delBtn && isEditing) {
    deleteAlbumEntry(Number.parseInt(delBtn.dataset.deleteIdx, 10));
    return;
  }

  const btn = event.target.closest('.year-rank-btn');
  if (btn && isEditing) {
    const fromIndex = Number.parseInt(btn.dataset.rank, 10);
    const delta = btn.dataset.move === 'up' ? -1 : 1;
    swapYearRank(fromIndex, fromIndex + delta);
    return;
  }

  const listenBtn = event.target.closest('[data-listen]');
  if (!listenBtn) return;
  const index = Number.parseInt(listenBtn.dataset.listen, 10);
  playYearAlbum(index);
});

const editToggle = document.getElementById('year-edit-toggle');
if (editToggle) {
  editToggle.addEventListener('click', () => {
    isEditing = !isEditing;
    editToggle.classList.toggle('is-active', isEditing);
    editToggle.textContent = isEditing ? 'Done ranking' : 'Edit ranking';
    renderList();
  });
}

renderYearNav();
renderList();

const isLocal = ['localhost', '127.0.0.1', ''].includes(location.hostname);
if (isLocal) {
  document.body.classList.add('is-local');
}

document.getElementById('mini-player-close').addEventListener('click', closeMiniPlayer);

// ── ADD / EDIT ALBUM MODAL ──
let _aapEditIdx = null; // null = new, number = editing existing entry

function openAddAlbumModal(editIdx) {
  _aapEditIdx = (editIdx !== undefined) ? editIdx : null;
  const isEdit = _aapEditIdx !== null;
  const entry  = isEdit ? ENTRIES[_aapEditIdx] : null;

  document.getElementById('aap-title').textContent = isEdit ? 'Edit album' : 'Add album';
  document.getElementById('aap-album-title').value = entry ? entry.title  : '';
  document.getElementById('aap-artist').value       = entry ? entry.artist : '';
  document.getElementById('aap-year').value         = entry ? entry.year   : (activeYear || new Date().getFullYear());
  document.getElementById('aap-art').value          = entry ? (entry.art || '') : '';
  document.getElementById('aap-audio').value        = entry ? (entry.audio || '') : '';
  document.getElementById('aap-tagline').value      = entry ? (entry.tagline || '') : '';
  document.getElementById('aap-review').value       = entry ? (entry.review || '') : '';

  _aapUpdateArtPreview(entry ? entry.art : '');

  // Every album here is deletable now - removing one no longer touches the timeline.
  document.getElementById('aap-delete-btn').style.display = isEdit ? '' : 'none';

  document.getElementById('add-album-overlay').style.display = 'block';
  document.getElementById('add-album-panel').style.display   = 'flex';
  document.getElementById('aap-album-title').focus();
}

function closeAddAlbumModal() {
  document.getElementById('add-album-overlay').style.display = 'none';
  document.getElementById('add-album-panel').style.display   = 'none';
  _aapEditIdx = null;
}

function saveAddAlbumModal() {
  const title  = document.getElementById('aap-album-title').value.trim();
  const artist = document.getElementById('aap-artist').value.trim();
  const year   = parseInt(document.getElementById('aap-year').value, 10) || activeYear;
  const art    = document.getElementById('aap-art').value.trim();
  const audio  = document.getElementById('aap-audio').value.trim();
  const tagline = document.getElementById('aap-tagline').value.trim();
  const review  = document.getElementById('aap-review').value.trim();

  if (!title) { document.getElementById('aap-album-title').focus(); return; }

  if (_aapEditIdx !== null) {
    // Editing an existing entry in-place
    const entry = ENTRIES[_aapEditIdx];
    entry.title   = title;
    entry.artist  = artist;
    entry.year    = year;
    entry.art     = art;
    entry.audio   = audio;
    entry.tagline = tagline;
    entry.review  = review;
  } else {
    // A new album belongs to this view alone; era/movement were timeline placement and
    // no longer apply. `review` used to be listed twice here, the second an empty string,
    // so anything typed into the review box when ADDING an album was silently discarded.
    ENTRIES.push({
      type: 'album',
      year,
      title,
      artist,
      tagline,
      art,
      audio,
      tier: '',
      artBg: '#181818',
      artColor: '#999',
      tags: [],
      review,
      context: '',
      tracks: [],
    });
  }

  persist();
  closeAddAlbumModal();
  renderYearNav();
  renderList();
}

function deleteAlbumEntry(entryIdx) {
  const entry = ENTRIES[entryIdx];
  if (!entry) return;
  if (!confirm(`Delete "${entry.title}"?`)) return;
  DELETED_KEYS.add(entryKey(entry));
  ENTRIES.splice(entryIdx, 1);
  persist();
  renderYearNav();
  renderList();
}

function _aapUpdateArtPreview(url) {
  const prev = document.getElementById('aap-art-preview');
  if (!prev) return;
  if (url) {
    prev.innerHTML = `<img src="${url}" onerror="this.parentElement.textContent='🎵'">`;
  } else {
    prev.textContent = '🎵';
  }
}

// This view used to have no export of its own - edits here rode along in the timeline's
// "⬇ data.js" button, because both views shared one array. After the fork that button
// only writes the timeline's entries, so Best of Year needs its own way to disk or its
// albums would live in localStorage and never reach the repo.
function saveBestOfDataJs() {
  const content =
    '// Albums for the Best of Year view (best-of-year.html).\n'
    + '//\n'
    + '// Deliberately separate from data.js: the two views were forked so that an album\n'
    + '// can be deleted, reordered or re-rated in one without touching the other. Albums\n'
    + '// that appear in both timelines exist as independent copies here - editing one side\n'
    + '// does not change the other.\n'
    + 'const BEST_OF_ENTRIES = ' + JSON.stringify(ENTRIES, null, 2) + ';\n'
    // YEAR_NOTES lives in this file too, so it has to be written back out - otherwise one
    // click of this button would silently drop every year summary on the floor.
    + '\n// One-paragraph summary per year, shown under the title on best-of-year.html.\n'
    + '// Written to describe the albums actually on each list, so revisit the text when a\n'
    + "// year's selections change substantially.\n"
    + 'const YEAR_NOTES = ' + JSON.stringify(typeof YEAR_NOTES !== 'undefined' ? YEAR_NOTES : {}, null, 2) + ';\n';

  const blob = new Blob([content], { type: 'text/javascript;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'bestof-data.js';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  // Bust the cache on the next deploy, the same way saveDataJs() does for the timeline.
  const v = Date.now();
  fetch('best-of-year.html')
    .then(r => r.text())
    .then(html => {
      const updated = html.replace(/(<script\s+src="bestof-data\.js)(\?v=[^"]*)?(")/, '$1?v=' + v + '$3');
      const b = new Blob([updated], { type: 'text/html;charset=utf-8' });
      const u = URL.createObjectURL(b);
      const link = document.createElement('a');
      link.href = u;
      link.download = 'best-of-year.html';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(u);
    })
    .catch(() => {
      console.warn('Could not auto-update best-of-year.html version — update bestof-data.js?v= manually if cache is stale');
    });
}

// Wire up modal buttons
document.getElementById('year-add-btn').addEventListener('click', () => openAddAlbumModal());
document.getElementById('year-save-btn').addEventListener('click', saveBestOfDataJs);
document.getElementById('aap-close').addEventListener('click', closeAddAlbumModal);
document.getElementById('aap-cancel-btn').addEventListener('click', closeAddAlbumModal);
document.getElementById('add-album-overlay').addEventListener('click', closeAddAlbumModal);
document.getElementById('aap-save-btn').addEventListener('click', saveAddAlbumModal);
document.getElementById('aap-delete-btn').addEventListener('click', () => {
  if (_aapEditIdx !== null) {
    closeAddAlbumModal();
    deleteAlbumEntry(_aapEditIdx);
  }
});

// Live art preview
document.getElementById('aap-art').addEventListener('input', e => {
  _aapUpdateArtPreview(e.target.value.trim());
});
